name: Build dependabot PRs
on:
  pull_request:
    branches: [ develop ]

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
            path: node_modules
            key: ${{ runner.os }}-npm-cache
            restore-keys: |
              ${{ runner.os }}-npm-cache
      - name: Install Dependencies
        run: yarn install
      - name: Prepare Environment File
        run: mv ops/docker/app/.env.production .env.production
      - name: Run Tests
        run: yarn test
      - name: Build App
        run: yarn build --verbose
        env:
          CI: false
