version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ../../
      dockerfile: ops/docker/app/Dockerfile
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_NAME=${REACT_APP_NAME}
    ports:
      - '3000:3000'
    networks:
      default:
        aliases:
          - rick-and-morty.local

volumes: {
  node_modules
}